name: AWS Account Creation

on:
  push:
    branches:
      - main

jobs:
  create-account:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new AWS Account
        run: |
          aws organizations create-account --email "newaccount@example.com" --account-name "NewAccount" --role-name "OrganizationAccountAccessRole"
